source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minimal-mistakes-jekyll"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "kramdown-parser-gfm"
gem "webrick"
